Remove guard
All rake tasks error due to:

LoadError: cannot load such file -- guard/guard

If anyone still uses guard in their workflow, please make sure rake
tasks run before re-adding it.

Change-Id: If74f4aedb1bd7b1628956008984fd86e52d99c9c